/* Registro central de íconos: los datos referencian una clave string y los
   componentes resuelven el componente de lucide-react desde acá. */
import {
  Wifi,
  Luggage,
  Coffee,
  Bath,
  ShieldCheck,
  Wallet,
  Car,
  BellRing,
  Plug,
  Utensils,
  Snowflake,
  Tv,
  Tag,
  Users,
  CalendarCheck,
  ScanLine,
  Accessibility,
  Brain,
  Ear,
  Ticket,
  Info,
  Bus,
  TramFront,
  TreePine,
  BookOpen,
  Armchair,
  MoveVertical,
} from 'lucide-react'

export const icons = {
  wifi: Wifi,
  luggage: Luggage,
  cafe: Coffee,
  bano: Bath,
  shield: ShieldCheck,
  wallet: Wallet,
  taxi: Car,
  alerta: BellRing,
  enchufe: Plug,
  snack: Utensils,
  aire: Snowflake,
  tv: Tv,
  descuento: Tag,
  familia: Users,
  reserva: CalendarCheck,
  id: ScanLine,
  movilidad: Accessibility,
  cognitiva: Brain,
  personal: Users,
  audio: Ear,
  boleteria: Ticket,
  informes: Info,
  embarque: Bus,
  subte: TramFront,
  parque: TreePine,
  libreria: BookOpen,
  asiento: Armchair,
  rampa: MoveVertical,
}

export function getIcon(key) {
  return icons[key] ?? Info
}
